version: "3.9"
services:
  api: 
    container_name: api
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    command: sh -c "/wait && 
            node util/create_db.js &&
            node util/seed_bd.js &&
            node app.js"

  mysql: 
    container_name: mysql
    env_file: .env
    image: mysql
    restart: unless-stopped
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 
